# Generated by Django 5.2.7 on 2025-10-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_certification_introduction_education_duration_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
