# Generated by Django 5.2.7 on 2025-10-18 14:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_certification_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="The title of the phase (e.g., 'Phase 1: Academic Base').", max_length=255)),
                ('order', models.PositiveIntegerField(help_text='The sequence in which the phase occurs in the roadmap.')),
                ('duration_months', models.IntegerField(default=0, help_text='Estimated duration of this phase in months.')),
                ('roadmap', models.ForeignKey(help_text='The career roadmap this phase belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='API.roadmap')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('roadmap', 'order')},
            },
        ),
        migrations.CreateModel(
            name='PhaseContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(help_text='Detailed description of the goals/actions in this phase.')),
                ('achieved_specializations', models.ManyToManyField(blank=True, to='API.specialization')),
                ('phase', models.ForeignKey(help_text='The specific phase this requirement is part of.', on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='API.phase')),
                ('required_certifications', models.ManyToManyField(blank=True, to='API.certification')),
                ('required_education', models.ManyToManyField(blank=True, to='API.education')),
                ('required_skills', models.ManyToManyField(blank=True, to='API.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
