# Generated by Django 5.2.7 on 2025-10-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_certification_description_phase_phasecontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='duration_months',
        ),
        migrations.AddField(
            model_name='phase',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the goals/actions in this specific phase.', null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='required_certifications',
            field=models.ManyToManyField(blank=True, help_text='Professional certifications obtained in this phase.', related_name='phases_required', to='API.certification'),
        ),
        migrations.AddField(
            model_name='phase',
            name='required_education',
            field=models.ManyToManyField(blank=True, help_text='Educational paths specifically completed or started in this phase.', related_name='phases_required', to='API.education'),
        ),
        migrations.AddField(
            model_name='phase',
            name='required_skills',
            field=models.ManyToManyField(blank=True, help_text='Skills that must be acquired or mastered in this phase.', related_name='phases_required', to='API.skill'),
        ),
        migrations.AddField(
            model_name='phase',
            name='required_specializations',
            field=models.ManyToManyField(blank=True, help_text='Specializations that are typically achieved or started in this phase.', related_name='phases_required', to='API.specialization'),
        ),
        migrations.DeleteModel(
            name='PhaseContent',
        ),
    ]
